# Basic
title: rovinder
subtitle: 个人站
description: autumnswing
# 头像里面的标题
avatarTitle: leopardpan
# 头像里面的描述
avatarDesc: iOS / 机器学习
url: "http://autumnswing.github.io"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: null 
    github: autumnswing
    # zhihu: panpanleopard
    # juejin: xxx
    jianshu: null
    # twitter: 
    mail: leoking02@foxmail.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 0e731faee82e4fd0b60e58f7700c08cc

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#     id: UA-84134159-3  
#     host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 技术支持, description: support, url: '/support'}      
    - {title: 关于我, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


